### ISSUE TITLE
Feature Request -> Multiple positions with one request

### ISSUE THREAD

**Issue by ghcr** [niklasf/lila-tablebase#41]
It would be nice if there is an option to request multiple positions at one time, for speed reasons.

So my chess engine uses a 5 peace tablebase (since 1 gig can fit in an raspberry pi ram), but it would be nice if my engine can request (around 30) endgame positions, in witch an 8 peace position may result to.

So the engine can decide witch peace to capture to get into an winning tablebase position.

**Comment by niklasf** [comment]
Sorry, I don't think probing in a chess engine is a reasonable use case for this API.

For the chess engine, there are usually many more than 30 subtly different ways to convert to a 7-piece endgame, so even the requested API wouldn't help much. Additionally, experiments with Stockfish show that even HDD/SSD latency can make a difference between lost/gained strength due to tablebase probing times. Going over the network seems completely impractical.

For the server, I'd prefer to use the limited I/O bandwidth for human analysis and research.
